services:
  db:
    image: postgres:15
    container_name: comments_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: comments_server
    restart: always
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://postgres:secret_password@db:5432/comments
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/server/uploads
      - ./temp:/app/server/temp

volumes:
  pgdata:
