services:
  db:
    image: postgres:15
    container_name: comments_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  server:
    build:
      context: ./server
    container_name: comments_server
    restart: always
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    depends_on:
      - db
    ports:
      - "3001:3001"
    volumes:
      - ./uploads:/app/uploads
      - ./temp:/app/temp

  client:
    build:
      context: ./client
    container_name: comments_client
    restart: always
    ports:
      - "80:80"
    depends_on:
      - server

volumes:
  pgdata: